### ISSUE TITLE
Issue with the No Decoration appearance style

### ISSUE THREAD

**Issue by HellKnightX88** [piroor/tst-indent-line#1]
Is it possible that this might not be working with the No Decoration appearance style of TST?
Seems to work with the 4 other styles  but whenever I switch to the No Decorations one it doesn't. Tried removing all my own styling edits to it and still nothing.

**Comment by 7vq** [comment]
Anyone know how to change the highlighted indent color like the Proton theme does?

<br />

I checked TST's proton.css and tried a few thing without luck.

**Comment by piroor** [comment]
@7vq Could you describe the expected appearance with edited screenshot?

**Comment by 7vq** [comment]
At the moment I only have the non-active indent lines colored (blue), while the current indent level is white. This doesn't give great contrast, so I'd like to be able to specify a color different than white. This is what I have currently:

![Screen Shot 2022-10-26 at 4 42 28 PM](https://user-images.githubusercontent.com/28467647/198145251-ee1c2520-adc0-4371-bb90-841b33ecbc1b.png)

**Comment by piroor** [comment]
I've released the version 1.2.2 with a change to make line colors changeable easily. For example:

```css
tab-item: {
  --indent-line-color: blue;
  --indent-line-color-active: aqua;
}
```

**Comment by 7vq** [comment]
@piroor Thanks! Unfortunately that doesn't change any colors for me. I tried it starting with 1.2.2 way back, hoping it would work on a restart. It doesn't work now with 1.2.3 either. It also doesn't work on a new, blank Firefox profile. I tried with and without the earlier `tab-border` rule above.

The original `tab-border` approach does still change the color, but also still doesn't let me change the active indent color, which would help me a ton.
